### ISSUE TITLE
regression: devel docs in nim-lang.github.io `Source` links point to master instead of devel 

### ISSUE THREAD

**Issue by timotheecour** [timotheecour/Nim#11]
seems like https://github.com/nim-lang/Nim/issues/9295 was closed but is happening again
https://nim-lang.org/docs/critbits.html

clicking on source points to a bad location https://github.com/nim-lang/Nim/blob/master/lib/pure/collections/critbits.nim#L236 
```
iterator mpairs[T](c: var CritBitTree[T]): tuple[key: string, val: var T]
yields all (key, value)-pairs of c. The yielded values can be modified.   Source Edit
```

EDIT: https://github.com/nim-lang/Nim/pull/11540 is related but doesn't fix this IIUC

**Comment by ringabout** [comment]
This issue seems to be fixed already.

**Comment by timotheecour** [comment]
closing, thanks !
