### ISSUE TITLE
$(-0.0) prints as -0.0; should that print as 0.0?

### ISSUE THREAD

**Issue by timotheecour** [timotheecour/Nim#136]
$(-0.0) prints as -0.0; should that print as 0.0?

### Example
```nim
proc main()=
  var a = -0.0
  echo a
  echo -0
  echo $(-0.0)
  var b = a
  echo b
  echo cast[uint](a)

static: main()
main()

```

### Current Output
```
-0.0
0
-0.0
-0.0
9223372036854775808
```

### Expected Output
* unclear whether we should print -0.0 as 0.0

### Additional information
* potentially an issue if 0.0==-0.0 but their `$` is different
* related: hashes.hash returns same hash for both
* nim js inconsistent with nim c,vm 
* see nimFloatToString in https://github.com/nim-lang/Nim/pull/14134
* TODO: look at how other PL do
* 9384f7ad35aa36a22b31d7541254e89890d6cec2
* D20200426T193533

**Comment by ringabout** [comment]
It differs in JS backend

```nim
proc main()=
  var a = -0.0
  echo a
  echo -0
  echo $(-0.0)
  var b = a
  echo b

static: main()
main()
```

output:
```
-0.0
0
-0.0
-0.0

0.0
0
-0.0
0.0
```

**Comment by timotheecour** [comment]
fixed by https://github.com/nim-lang/Nim/pull/16505 ; thanks!
