### ISSUE TITLE
azure pipelines restart failed job

### ISSUE THREAD

**Issue by timotheecour** [timotheecour/Nim#211]
this should be in https://nim-lang.github.io/Nim/contributing.html :
restarting a failed job (eg bc of a flaky test) on azure pipelines can be done as follows:
* if on your own fork, it's possible from inside azure console (eg https://dev.azure.com/timotheecour/timotheecour/_build/results?buildId=1430&view=results) via "rerun failed jobs"
* if either on you own fork on in Nim repo, it's possible from inside github UI under `checks` tab, see https://github.com/timotheecour/Nim/issues/211#issuecomment-629751569

##
on my nim fork:

![image](https://user-images.githubusercontent.com/2194784/82137607-8e057180-97ce-11ea-9ce8-8bf0fdd860ae.png)

on nim repo:
![image](https://user-images.githubusercontent.com/2194784/82137617-9f4e7e00-97ce-11ea-81a8-272051312819.png)

**Comment by timotheecour** [comment]
![image](https://user-images.githubusercontent.com/2194784/82137655-e76da080-97ce-11ea-809e-eca35f7c6335.png)


![image](https://user-images.githubusercontent.com/2194784/82137647-d755c100-97ce-11ea-85c9-a89e03abf96c.png)

**Comment by ringabout** [comment]
already fixed
