### ISSUE TITLE
add section under contributing on how to restart CI in a resource effective way

### ISSUE THREAD

**Issue by timotheecour** [timotheecour/Nim#327]
force pushing or closing/re-opening PR to re-run when a job is flaky (or when something external changed, like an important_package) re-runs CI for everything including jobs that shouldn't be restarted; instead, one can do a more targeted re-run as follows:

it differs for azure vs github vs buildshrt

* azure: https://github.com/timotheecour/Nim/issues/211
* buildshrt: create a sourcehut account and you can
https://github.com/nim-lang/Nim/pull/14801#issuecomment-650297728

* github actions: [rerunning CI works for github actions, sr.ht, but not azure pipelines - Nim forum](https://forum.nim-lang.org/t/6333#39112)

## pic for buildshrt
=> click on resubmit build (requires creating sourcehut account)

![image](https://user-images.githubusercontent.com/2194784/86290186-de2f6c00-bba1-11ea-8c25-88f82a8694ed.png)

**Comment by ringabout** [comment]
already fixed
