### ISSUE TITLE
support addInt for uint64 (not just int64)

### ISSUE THREAD

**Issue by timotheecour** [timotheecour/Nim#406]
refs https://github.com/nim-lang/Nim/pull/16160

```nim
when true:
  var a: string
  a.addInt(uint64.high)
```

Error: type mismatch: got <string, uint64>
but expected one of:
proc addInt(result: var string; x: int64) [proc declared in /Users/timothee/git_clone/nim/Nim_prs/lib/system/strmantle.nim(98, 6)]

## example use case
would avoid in https://github.com/nim-lang/Nim/pull/15935/files
```nim
of externUIntLit:
    result.add " "
    result.add $cast[uint64](tree.sh.integers[LitId tree.nodes[pos].operand])
```

## links
[better $uint64 by xflywind · Pull Request #16194 · nim-lang/Nim](https://github.com/nim-lang/Nim/pull/16194)

**Comment by xflywind** [comment]
Now https://github.com/nim-lang/Nim/pull/18318 was merged. Closing.

**Comment by timotheecour** [comment]
> Now nim-lang#18318 was merged. Closing.

ya it still is a problem (i guess you deleted this comment now?)

**Comment by ringabout** [comment]
merged
