### ISSUE TITLE
rfactor and fix the 5 different (buggy) re-implementations of cmpIgnoreStyle

### ISSUE THREAD

**Issue by timotheecour** [timotheecour/Nim#472]
the ones that are actually intended to be case insensitive should be renamed to something else, or cmpIgnoreStyle can get an extra param `caseInsensitive = false`

## links
https://github.com/nim-lang/Nim/pull/16391
https://github.com/nim-lang/Nim/pull/16392

**Comment by ringabout** [comment]
I already plan to refactor them and place them in std/private/str*. Use templates so that make cstrutils support JS backend.

**Comment by timotheecour** [comment]
@xflywind
cool!

> Use templates so that make cstrutils support JS backend.

can be discussed in your PR, but here's how to get best of both worlds:
* avoid code bloat (C optimizer is free to either inline or keep as separate proc)
* keep implementation DRY
* works in js, vm, c:

```nim
# proc fn[T: openArray[char] or cstring](a: T) = # nim BUG: this doesn't work

template fnImpl(a): untyped =
  # xxx: actual impl goes here
  for ai in a: echo (ai,)

proc fn(a: openArray[char]) = fnImpl(a)
proc fn(a: cstring) = fnImpl(a)
proc fn(a: string) = fnImpl(a)

proc main()=
  fn("abc")
  var b = "abc".cstring
  fn(b)
  fn(['a','b'])

main()
static: main()
```

**Comment by ringabout** [comment]
I won't consider VM backend in this PR too much.
I could clean up this in the next PR(`cstrutils` doesn't support VM currently. It needs more cares to make it work).

**Comment by ringabout** [comment]
Maybe we also need `cmpNimIdentifier`.

**Comment by ringabout** [comment]
- [x] Refactor `startsWith` and `endsWith`
- [x] Make `cstrutils` support VM
- [x] Write more functions to `cstrutils`
- [x] Add `strutils.cmpNimIdentifier`
