### ISSUE TITLE
can we support UFCS/MCS for `ForLoopStmt` macros?

### ISSUE THREAD

**Issue by timotheecour** [timotheecour/Nim#473]
Currently we can't use UFCS/MCS for `ForLoopStmt` macros, eg:
```nim
import std/enumerate
for a in enumerate([1,2]): discard # ok
for a in [1,2].enumerate: discard # doesn't work
for i,ai in [1,2]: discard # ok but that's not the point of this RFC
```

enumerate uses `ForLoopStmt` and `ForLoopStmt` allows taking an untyped AST, including: `for a in myForLoop(nonexistant): discard`, so we can't simply semcheck `foo` in `for a in foo.bar: ...`

## proposal
```nim
macro bar*(x: ForLoopStmt): untyped = ...
for a in foo.bar: discard
```

the compiler tries 2 interpretations:
* `items(foo.bar)` as iterable
* `bar(foo)` as iterable

if only one of these semchecks, it accepts it
if both of these semchecks, it gives an ambiguity error
if neither semchecks, it gives an error

## general macros
More generally, maybe we can support MCS/UFCS for untyped macros in a similar way.

## links
this came up here: https://github.com/nim-lang/Nim/pull/16362#issuecomment-748444313

**Comment by c-blake** [comment]
I am in favor of adding postfix call syntax for for loop macros.  Besides `enumerate`, I find `toItr` a good use case example (mentioned 3 or 4 times in the Nim forum, added to the manual, implemented in `cligen/sysUt.nim`).  Something about the `for x... in y(a,b).toItr:` with the `toItr` and `':'` being lexically adjacent just looks nice to me.

I'm not sure your proposed impl idea is best, but I also have no competing suggestion.

**Comment by timotheecour** [comment]
superseded by https://github.com/nim-lang/RFCs/issues/345 which is a strictly better proposal:
* uses regular sigmatch, no need for special behavior
* more general since also allows overloading based on type

(it also would handle `for x... in y(a,b).toItr` without any particular problem)
