### ISSUE TITLE
needed libraries

### ISSUE THREAD

**Issue by ringabout** [timotheecour/Nim#481]
wrapper xlsxio   https://github.com/brechtsanders/xlsxio
port vsl to Nim  https://github.com/vlang/vsl
port replxx - A readline and libedit   https://github.com/AmokHuginnsson/replxx
FortAwesome wrapper https://github.com/FortAwesome

**Comment by timotheecour** [comment]
merge into https://github.com/timotheecour/Nim/issues/181 or different issue?

**Comment by ringabout** [comment]
> merge into #181 or different issue?

sure
