### ISSUE TITLE
unbundle fusion from nim

### ISSUE THREAD

**Issue by timotheecour** [timotheecour/Nim#538]
refs
* [instead of copyDir(fustion, stdlib/lib), update --path · Issue #25 · nim-lang/fusion](https://github.com/nim-lang/fusion/issues/25)
* [Fusion and stdlib evolution · Issue #310 · nim-lang/RFCs](https://github.com/nim-lang/RFCs/issues/310)

**Comment by ringabout** [comment]
I would prefer something like [boost](https://www.boost.org).

**Comment by ringabout** [comment]
done

**Comment by timotheecour** [comment]
@xflywind what would make fusion more like boost?
