### ISSUE TITLE
mitems with start

### ISSUE THREAD

**Issue by juancarlospaco** [timotheecour/Nim#579]
Working on improving the `random.sampleBuffer`, I made this change:

```nim
proc sampleBuffer*[T](r: var Rand, buffer: var openArray[T]; alphabet: set[T]; start = 0.Natural) =
  # for c in buffer.mitems: c = sample(r, alphabet)              # OLD code.
  for i in start .. buffer.len: buffer[i] = sample(r, alphabet)  # See "start".
```

I need a `mitems` but that takes a `start: Natural` argument, but no such overload exists,
would be very nice because `mitems` tends to be used for in-place good performance loops!

https://nim-lang.github.io/Nim/iterators.html#mitems.i%2Carray%5BIX%2CT%5D

What if I have a gigabyte sized iterable but only want to iterate only the last 9 items ?.

- Add an overload to `mitems` that takes 1 extra argument `start: Natural`.
- Or a range `0..9` being `start..end`, but with the `start` at least is Ok.

The code of `mitems` is not massively complex, should be easy to implement.

```nim
iterator mitems*[T](a: var openArray[T]): var T {.inline.} =
  var i = 0
  while i < len(a):
    yield a[i]
    inc(i)
```

Not only performance, but consistency and correctness of the code, 
switching `mitems` with `for i in start..end` and back again is just wrong.

**Comment by timotheecour** [comment]
but openArray can be sliced (modulo some backend specific bugs, see https://github.com/nim-lang/Nim/issues/15952); assuming https://github.com/nim-lang/Nim/issues/15952) is fixed, doesnt' `a.toOpenArray(start, end)` subsume your proposal?

**Comment by juancarlospaco** [comment]
`toOpenArray` is `iterator` and `{.inline.}` ?. :thinking:

**Comment by timotheecour** [comment]
instead of:
```nim
proc sampleBuffer*[T](r: var Rand, buffer: var openArray[T]; alphabet: set[T]; start = 0.Natural) = ...
sampleBuffer(r, buf, alpha, start = 2)
```

use:
```nim
proc sampleBuffer*[T](r: var Rand, buffer: var openArray[T]; alphabet: set[T]) = ...
sampleBuffer(r, buf.toOpenArray(2, buf.high), alpha)
```

**Comment by juancarlospaco** [comment]
Then this bug is kinda fixed.

- But would be nice to document that, on the `mitems` documentation.

**Comment by timotheecour** [comment]
> But would be nice to document that, on the mitems documentation.

not sure it belongs to mitems documentation, toOpenarray likewise can be used in other contexts (eg items and plenty other places). But we should definitely fix https://github.com/nim-lang/Nim/issues/15952
