### ISSUE TITLE
Error: return type 'auto' cannot be used in forward declarations

### ISSUE THREAD

**Issue by juancarlospaco** [timotheecour/Nim#583]
```console
$ cat example.nim 
func x(): any {.importjs: "console.log(42)".}

$ nim js example.nim 
Hint: 42236 lines; 0.100s; 49.152MiB peakmem; Debug build; proj: example.nim; out: example.js [SuccessX]

$ cat example2.nim 
func x(): auto {.importjs: "console.log(42)".}

$ nim js example2.nim 
example2.nim(1, 11) Error: return type 'auto' cannot be used in forward declarations
```

/cc @timotheecour

**Comment by timotheecour** [comment]
IMO it's just a matter of detecting that we have a importc/importjs/importcpp declaration, and issuing a better error message eg:
```
Error: return type 'auto' cannot be used in importc declarations
```
unless you have a better idea

**Comment by juancarlospaco** [comment]
But return type `any` is useful for JS, because some api return mixed types arbitrarily. :thinking:  

I think that if `auto` is meant to replace `any` then it should be allowed on importjs/importc/importcpp, `any` works Ok.

**Comment by timotheecour** [comment]
> But return type any is useful for JS,

calling such a proc doesn't work:
```
func x(): any {.importjs: "console.log(42)".}
x() # Error: invalid type: 'GenericParam' in this context: 
```

> because some api return mixed types arbitrarily

i don't understand what you mean by that. nim return type must be statically known, it can't be dynamic (`JsRoot* = ref object of RootObj` is a static type)

`auto` is more confusing than helpful, user should type `void` or some explicit type.
`auto` is only useful for type inference.

In future work we might actually support `auto` in importc procs to mean something different: inferring type from looking at the generated code, calling into backend compiler and converting return type into a nim type; but that's hypothetical.

**Comment by juancarlospaco** [comment]
The code was just an example.

Ok, but I think that before removing `any`, the `auto` should be able to replace it.

**Comment by timotheecour** [comment]
> The code was just an example.

what do you mean `just an example`? can you come up with a working example with `any` return type in a importc/fwd declaration? I don't see how it could work (other that special type inference discussed in https://github.com/timotheecour/Nim/issues/583#issuecomment-776270569)

IMO that's just a bug with `any`, which may not be worth fixing if it's going to be deprecated/removed; but the error message for `auto` can be improved though.
