### ISSUE TITLE
seq.delete broken

### ISSUE THREAD

**Issue by juancarlospaco** [timotheecour/Nim#604]
```nim
var a: seq[int] = @[0]
a.delete(999999999999)
```

```nim
var a: seq[int] = @[0]
discard a.pop()
a.delete(999999999999)
```

```nim
var a: seq[int] = @[0]
discard a.pop()
a.insert(42, 0)
a.delete(999999999999)
```

`del` works consistently on all cases:

`Error: unhandled exception: index out of bounds, the container is empty [IndexDefect]` or similar.

- Make `delete` and `del` check index out of bounds consistently, at least for non-Danger builds, Fix should include at least 1 test.

**Comment by ringabout** [comment]
duplicated
https://github.com/nim-lang/Nim/issues/16544

**Comment by juancarlospaco** [comment]
Strange is that the one with the `pop()` works different.
