### ISSUE TITLE
typesafe time units: `proc sleep(t: Duration)`, allowing `sleep(1.second)`, `sleep(1.millisecond)` etc

### ISSUE THREAD

**Issue by timotheecour** [timotheecour/Nim#617]
as noted in https://github.com/nim-lang/Nim/pull/17149#discussion_r580737692, `sleep` is confusing:
* posix.sleep takes seconds
* os.sleep takes milliseconds

this is confusing, not self documenting, error prone and not particularly typesafe

## proposal
add `proc sleep(t: Duration)`
example:
```nim
sleep(1.second)
sleep(1.millisecond)
sleep(100.millisecond + 1.second)
sleep(1.5.hour)
```

## note
std/times is a heavy dependency, ideally we'd be able to do this without depending on std/times, refs https://github.com/nim-lang/RFCs/issues/55, via a new std/durations module (imported by std/times)

## note
`TimeInterval` is not good, this has overhead because it's calendar based
we can define `millisecond`, `second` (etc) without `s` to avoid confusion with the existing `milliseconds` + friends.
eg:
```nim
proc second*(a: int | float): Duration
proc millisecond*(a: int | float): Duration
# etc
```

**Comment by ringabout** [comment]
Now, we could have

```nim
sleep(1'second)
sleep(1'millisecond)
sleep(100'millisecond + 1'second)
sleep(1.5'hour)
```

Consider following APIs

## sleepFor

```nim
proc sleepFor(t: Duration)
```

The thread blocks for at least specified duration.

## sleepUntil

```nim
proc sleepUntil(t: DateTime)
```

The thread blocks until specified time arrived.

**Comment by timotheecour** [comment]
> Now, we could have

yes.

> sleepFor, sleepUntil

maybe sleepMin, sleepMax is less ambiguous? but also, can you explain the semantics of those 2 procs, and in which case you'd end up sleep more than sleepFor or less than sleepUntil?


also: std/durations should be separate from std/times and be imported/re-exported from std/times
(because std/times is a monster already and durations can be selfcontained and small); related to https://github.com/nim-lang/RFCs/issues/55

**Comment by timotheecour** [comment]
closing, as I'm opening the corresponding RFC https://github.com/nim-lang/RFCs/issues/383 (because I'm seeing PRs that introduce duration params as int)
