### ISSUE TITLE
investigate why some sourcehut builds are ran on my account instead of nim's account

### ISSUE THREAD

**Issue by timotheecour** [timotheecour/Nim#666]
@ddevault do you know why https://github.com/nim-lang/Nim/pull/17472 freebsd CI (https://builds.sr.ht/~timotheecour/job/467694) is ran on my sourcehut account (timotheecour's) account and openbsd on araq's (https://builds.sr.ht/~araq/job/467698) ? I did not have any interaction with that particular PR, I'd expect all CI in that PR to use araq's account.

note that this PR's CI was ran before the disabling of webhooks (refs https://github.com/nim-lang/Nim/issues/17479#issuecomment-805033950) which were disabled to address your resource usage concerns from https://github.com/nim-lang/Nim/issues/17479, so I don't think it's related to that.

(this issue was reported to me in https://irclogs.nim-lang.org/23-03-2021.html#13:45:19 ) so I'm trying to understand the root cause and if there's a configuration error on my end or nim's end or whether it's a glitch with sourcehut. Note that I've occasionally clicked on `resubmit build` in sourcehut UI for some PR's that had failed with a flaky test, but not recently, and not in that PR, so that's probably unrelated.

Thanks

**Comment by ddevault** [comment]
Do you have any tasks set up at https://dispatch.sr.ht ?

**Comment by ringabout** [comment]
well sourcehut is disabled for pull request
