### ISSUE TITLE
`runnableExamples` should be attacheable for any declaration (eg `const`)

### ISSUE THREAD

**Issue by timotheecour** [timotheecour/Nim#716]

**Comment by juancarlospaco** [comment]
Workaround, use a `func` with `{.compiletime.}` and put the `runnableExamples` there, sux.

**Comment by timotheecour** [comment]
well that changes semantics (need to call with `()`), but we should simply fix this, it can't be that hard

**Comment by timotheecour** [comment]
migrated to https://github.com/nim-lang/Nim/issues/18305
