### ISSUE TITLE
os.getHomeDir, os.getConfigDir, os.expandTilde returns trailing sep

### ISSUE THREAD

**Issue by juancarlospaco** [timotheecour/Nim#728]
```nim
import os
echo getTempDir()
echo getCurrentDir()
echo getAppDir()

echo getHomeDir()     # Trailing sep
echo getConfigDir()   # Trailing sep
echo expandTilde("~") # Trailing sep
```

Confirmed on Linux, I dunno Mac and Windows?.

Can repro on Playground too, returns `"//"`.

**Comment by timotheecour** [comment]
which git hash? is that after these were merged? https://github.com/nim-lang/Nim/pull/17398 https://github.com/nim-lang/Nim/pull/17402

**Comment by juancarlospaco** [comment]
You are right, is Fixed, sorry about the noise.
