### ISSUE TITLE
os.FileInfo.linkCount off by one

### ISSUE THREAD

**Issue by juancarlospaco** [timotheecour/Nim#729]
```nim
import os
writeFile "/tmp/a", "a"
doAssert getFileInfo("/tmp/a").linkCount == 1
```

It can not have `1` link if I just created it.
Can repro on Playground.

**Comment by timotheecour** [comment]
IMO this works correctly; if you create a hard link via `ln`, you'd increment the count to 2

**Comment by juancarlospaco** [comment]
A file is its own hardlink ?, ...Ok.
