### ISSUE TITLE
line wrapping

### ISSUE THREAD

**Issue by timotheecour** [timotheecour/Nim#734]
refs https://stackoverflow.com/questions/41238148/how-to-line-wrap-long-lines-inside-markdown-code-blocks-in-githubgitlab/67544049#67544049

### Example
```
some very long line; some very long line; some very long line; some very long line; some very long line; some very long line; some very long line; some very long line; some very long line; some very long line; 
```

refs https://stackoverflow.com/a/67544049/1426932

<style>
  code {
    white-space : pre-wrap !important;
  }
</style>

```
some very long line; some very long line; some very long line; some very long line; some very long line; some very long line; some very long line; some very long line; some very long line; some very long line; 
```

**Comment by juancarlospaco** [comment]
It is not working for me.
For what specifically ?.
Maybe we can open an issue on a project like https://github.com/softvar/enhanced-github

**Comment by timotheecour** [comment]
for me neither (i was trying to double check if a SO answer would work, refs https://stackoverflow.com/questions/41238148/how-to-line-wrap-long-lines-inside-markdown-code-blocks-in-githubgitlab/67544049?noredirect=1#comment119386193_67544049; it doesn't work in github issues is the conclusion)

> For what specifically ?.

wrapping long lines inside code blocks

**Comment by timotheecour** [comment]
> Maybe we can open an issue on a project like softvar/enhanced-github

done: https://github.com/softvar/enhanced-github/issues/95
