### ISSUE TITLE
nim doc crash oneliner

### ISSUE THREAD

**Issue by juancarlospaco** [timotheecour/Nim#739]
```console
$ choosenim update devel
   Updating devel
Downloading Nim latest-devel from GitHub
[##################################################] 100.0% 0kb/s
 Extracting linux_x64.tar.xz
    Setting up git repository
   Building Nim #devel
  Compiler: Already built
     Tools: Already built
    Updated to #devel
      Info: Version #devel already selected

$ cat example.nim
## .. warning:: `try`...`except`.

$ nim doc example.nim
example.nim(1, 32) Error: '`' expected
lineinfos.nim(261)       raiseRecoverableError
Error: unhandled exception: '`' expected [ERecoverableError]

$
```

Repro

```nim
## .. warning:: `try`...`except`.

```

I try to write documentation with something like

```nim
## .. warning:: This may raise use `try`...`except`.

```

Documentation is NOT generated.

Ping @a-mr

**Comment by timotheecour** [comment]
i can reproduce this indeed.

@juancarlospaco you can now use `--eval` to simplify such bug reports:
```
nim doc -r --eval:'## .. warning:: `try`...`except`.'
cmdfile.nim(1, 32) Error: '`' expected
7f077a76fea389ce4f55e18857c499fadb3958fa
```

or this:
```
echo '## .. warning:: `try`...`except`.' | nim doc -
```

**Comment by a-mr** [comment]
it's because in
```
...`except`
```
first \` before except is not recognized as markup start, while \` after except is, so this second \` is unmatched.

The reason is a weird rule for inline mark-up start string that is a mix for RST and Markdown:
- ` cannot be preceded by punctuation — borrowed from RST
- but it can be preceded by word —  borrowed from Markdown 

I'll fix that in my next PR.

**Comment by juancarlospaco** [comment]
I agree, if it is not a Bug then no problem, I know Markdown has no official standard spec.

**Comment by a-mr** [comment]
I thought it was a complete mess but it appeared not that bad: there is a [CommonMark](https://spec.commonmark.org/0.29/) spec for Markdown and GitHub seems to officially follow it (adding its own extensions).

Another thing that I don't really have plans to support Markdown in full, only some Markdown-ish behavior.

In this particular case it makes perfect sense to fix it according to Markdown rules.

**Comment by juancarlospaco** [comment]
https://github.com/nim-lang/Nim/pull/18053#issue-649563703
