### ISSUE TITLE
injectStmt not working?

### ISSUE THREAD

**Issue by juancarlospaco** [timotheecour/Nim#759]
- is injectStmt not working?

```nim
import std/jsconsole
console.log "BEFORE"
func example*() = {.emit: "console.log('injectStmt')".}
{.injectStmt: example().}
console.log "AFTER"
```

`nim js -r -d:danger -d:nodejs example.nim` gives:

```javascript
/* Generated by the Nim Compiler v1.5.1 */
var framePtr = null;
var excHandler = 0;
var lastJSError = null;
console.log("BEFORE");
console.log("AFTER");
```

Nothing is "injected", it is even working?.

Documentation is really bad for this, no examples https://nim-lang.github.io/Nim/manual.html#implementation-specific-pragmas-injectstmt-pragma

No real usages in the Nim repo https://github.com/nim-lang/Nim/search?q=injectStmt

If it is not working, then it should be deprecated, YAGNI.

**Comment by timotheecour** [comment]
=> https://github.com/nim-lang/Nim/pull/18300
