### ISSUE TITLE
Memory Leak os.putEnv

### ISSUE THREAD

**Issue by juancarlospaco** [timotheecour/Nim#783]
Python has a Warning in the documentation:

> Note: On some platforms, including FreeBSD and Mac OS X, setting environ may cause memory leaks. Refer to the system documentation for putenv().

- https://docs.python.org/3.10/library/os.html#os.putenv

Nim uses `putenv` from C:

- https://github.com/nim-lang/Nim/blob/devel/lib/pure/includes/osenv.nim#L224
- https://github.com/nim-lang/Nim/blob/devel/lib/pure/includes/osenv.nim#L48

StackOverflow recommends using `setenv` from C:

- https://stackoverflow.com/questions/4777909/how-does-one-maintain-memory-with-the-putenv-system-call

Nim needs a warning in the documentation too.

I do not have BSD nor Mac for repro, but because is using putenv from C should repro anyway.

**Comment by juancarlospaco** [comment]
@timotheecour You use Mac?, can you confirm or close. 🙂

**Comment by timotheecour** [comment]
you're right there is a bug:
```nim
import os
putEnv("foo=bar", "baz")
echo getEnv("foo")
```
prints: bar=baz

can you file an issue? 
maybe we should indeed stick to `setenv`

**Comment by timotheecour** [comment]
filed https://github.com/nim-lang/Nim/issues/18502, so I'm closing this, thanks!

**Comment by juancarlospaco** [comment]
Thanks to you too, for help confirming the Bug.
