### ISSUE TITLE
DocGen Regression inline proc doc

### ISSUE THREAD

**Issue by juancarlospaco** [timotheecour/Nim#784]
```console
$ cat example.nim
func example*(): int = 42  ## DOCUMENTATION HERE!.

$ choosenim 1.2.0
$ nim doc example.nim
```

![temp0](https://user-images.githubusercontent.com/1189414/125856525-7732c72c-4bda-4562-9c76-80dd80893d72.png)

```console
$ choosenim devel
$ nim doc example.nim
```

![temp1](https://user-images.githubusercontent.com/1189414/125856630-404d66b5-2f06-4e94-97ba-1210d87d8777.png)

DocGen completely removes documentation, single-line proc is useful for FFI purposes (importjs, importc, etc).

/cc @a-mr

**Comment by timotheecour** [comment]
I see; this is intimately tied to https://github.com/nim-lang/RFCs/issues/231; the problem is that the spec for placement of doc comments/runnableExamples is not well specified.

unclear what the right approach is here, if you consider other examples:

```nim
proc fn* =
  ## foo
  echo 1
  ## bar <= should this be part of doc comment? if not, what's the correct algorithm to decide?
```

**Comment by juancarlospaco** [comment]
Python takes 1 string on the first line of the body of the function, 
string can be multi-line, if it is placed elsewere it is always ignored.

I am Ok with whatever is choosed as standard, but better to choose a standard way of doing it. 🙂

**Comment by a-mr** [comment]
> what's the correct algorithm to decide?

Suggestion: if the line of equal sign `=` is `N` then any doc comment starting on `N` or `N+1` is good. So this is also correct:

```nim
func example*(): int = 42
  ## DOCUMENTATION HERE!.
```

This is **not** correct:

```nim
func example*(): int =
  42
  ## BAD
```

**Comment by timotheecour** [comment]
> Suggestion: if the line of equal sign = is N then any doc comment starting on N or N+1 is good. So this is also correct:

sounds reasonable; can you write a PR?

**Comment by juancarlospaco** [comment]
So single line proc doc will not work anymore?.

**Comment by a-mr** [comment]
@juancarlospaco ,
it will work if the suggestion gets applied because equal sign is on the same line as doc comment.

**Comment by a-mr** [comment]
@timotheecour ,

There may be another problem here: I don't see a doc comment saved in AST tree in the case of  same-line doc comment (example 1 below):
```nim
dumpTree:
  func example1*(): int = 42  ## DOCUMENTATION HERE!.
  func example2*(): int =
    ## DOCUMENTATION HERE!.
    43
  func example3*(): int =
    44
    ## DOCUMENTATION HERE!.
```

```
StmtList
  FuncDef
    Postfix
      Ident "*"
      Ident "example1"
    Empty
    Empty
    FormalParams
      Ident "int"
    Empty
    Empty
    StmtList
      IntLit 42
  FuncDef
    Postfix
      Ident "*"
      Ident "example2"
    Empty
    Empty
    FormalParams
      Ident "int"
    Empty
    Empty
    StmtList
      CommentStmt "DOCUMENTATION HERE!."
      IntLit 43
  FuncDef
    Postfix
      Ident "*"
      Ident "example3"
    Empty
    Empty
    FormalParams
      Ident "int"
    Empty
    Empty
    StmtList
      IntLit 44
      CommentStmt "DOCUMENTATION HERE!."
```


Also I doubt that position of equal sign is saved...

**Comment by timotheecour** [comment]
some more info:
* same line doc comment didn't work reliable in 1.2
```nim
func example2*(a: int): int = 42  ## DOCUMENTATION HERE2
func example3*(a: int): int = a  ## DOCUMENTATION HERE3
```
example2 worked in 1.2, but example3 didn't work in 1.2 (the doc comment disappears)

* this works both in 1.2 and devel 1.5.1 as of e08ec0c6745e54de4e174970e513acef3b0d8f5e:
```nim
func example4*(a: int): int = a
  ## DOCUMENTATION HERE3
```
* runnableExamples doesn't work but should (parser error):
both 1.2 and devel give: Error: invalid indentation
```nim
func example5*(a: int): int = a
  ## comment
  runnableExamples:
    let x = 1

func example6*(a: int): int = a
  runnableExamples:
    let x = 1
```

**Comment by juancarlospaco** [comment]
If you think is not a bug, because they never worked reliably, feel free to close no problem.

**Comment by timotheecour** [comment]
> If you think is not a bug, because they never worked reliably, feel free to close no problem.

I never said that :) things should improve regardless of whether they worked reliably in past or not

**Comment by timotheecour** [comment]
=> PR https://github.com/nim-lang/Nim/pull/18595
