### ISSUE TITLE
Compiler warning nested ref

### ISSUE THREAD

**Issue by juancarlospaco** [timotheecour/Nim#807]
I found this when explaining Nim to some new users, I think it does not make too much sense,
it is not very useful, looks bug prone and maybe the compiler can show a warning:

```nim
var x: ref ref ref ref ref ref ref ref ref ref ref ref ref ref ref ref ref ref ref ref ref ref ref ref ref int
echo x.type
```

I can not find any code anywhere that makes correct use of having deep nested `ref` types like these,
the compiler should emit a warning for deep nested `ref`. Even `echo x` and `dumpAstGen` breaks with that "type".
Actually a lot of stdlib breaks with "types" like these.

If I am wrong please show an example that uses 
`ref ref ref ref ref ref ref ref ref ref ref ref ref ref ref ref ref ref ref ref ref ref ref ref ref T` 
for something useful and relevant.

**Comment by timotheecour** [comment]
nothing to fix; ref ref is legal, there's no point in adding edge cases; if user wants to write dubious code, it's their problem, it doesn't cause actual problems

this is legal:
```nim
type A = ref object
type B = ref A
let b = B.new
echo b.type
```

**Comment by juancarlospaco** [comment]
Ok, accepted, but I would like to see a point where people can learn programming with Nim, 
without passing first thru Python or JavaScript, then warning messages for weird code makes sense...
